name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        os: [windows-latest]
        configuration: [Release]
        platform: [x64, x86, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --runtime ${{ matrix.platform }}

    - name: Test
      run: dotnet test --configuration ${{ matrix.configuration }}

    - name: Set release name and tag
      run: |
        echo "KuruTweak - $(date +'%Y.%m.%d')" > release_name.txt
        git tag -a "$(date +'%Y.%m.%d')" -m "Release $(date +'%Y.%m.%d')"
        git push origin --tags
