name: Automatic Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release

    - name: Publish artifact
      run: dotnet publish --configuration Release --output ./publish

    - name: Set date variable
      id: set_date
      run: echo "RELEASE_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        files: ./publish/**
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "KuruTweak - v${{ env.RELEASE_DATE }}"
        tag_name: "v${{ env.RELEASE_DATE }}"

    - name: Deploy manifestv3
      uses: owner/repo/deploy-action@v1
      with:
        environment: production
        token: ${{ secrets.GITHUB_TOKEN }}
